version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    env_file:
      - .env
    ports:
      - '5432:5432'
    # healthcheck:
    #   test: 'pg_isready --username=warehouse && psql --username=warehouse --list'
    #   interval: 5s
    #   timeout: 3s
    #   retries: 3
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./cmd/database/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql

  server:
    build: .
    env_file:
      - .env
    depends_on:
      - postgres
    restart: on-failure
    ports:
      - '8080:8080'

volumes:
  dbdata:
